### ISSUE TITLE
任何模式启动都需要点击三次以上

### ISSUE THREAD

**Issue by BlackieMei509** [houselabs/home-assistant-mideaccm#9]
你好，iPhone X的IOS13.1，HA版本群晖docker 0.97.0b3，在家庭应用和HA界面里开启制冷，或者关机等，都需要点击三次以上才能成功，麻烦您给看看

**Comment by BH4WHN** [comment]
你是用的homekit控制吗？如果用的ios版的homeassistant客户端应该是和电脑浏览器控制没差别的，那个app只是给web界面封装了一个壳。我没有遇到过点三次的问题，任何操作是有2秒左右的延时才会在空调上反馈出来这种是正常的，如果需要进一步帮助，请提供配置文件并说明运行环境。

**Comment by BlackieMei509** [comment]
在苹果的homekit界面里面，不是等待延迟，是点击为制热制冷这些模式以后自己回弹为关闭，空调反应是滴一声，开启出风口接着自动关闭出风口。连续3次以后才能启动成功。
在homeassistant里面操作一次就可以，不知道是什么原因。
iPhone X IOS 13.1
homeassistant运行环境：群晖DSM6.17，版本：0.101.2

\homeassistant\configuration.yaml
```
#美的CCM15
climate:
  - platform: ccm15
    name: mideaccm
    host: 192.168.1.200
    port: 80
    scan_interval: 10

```
